insert into CLASSES(ID,NAME,COMMENT,TYPE) values(null,"zoujinkexue ","z","kx");
insert into CLASSES(ID,NAME,COMMENT,TYPE) values(null,"guojiadili ","g","dl");
insert into CLASSES(ID,NAME,COMMENT,TYPE) values(null,"renleiqiyuan ","r","sh");
insert into CLASSES(ID,NAME,COMMENT,TYPE) values(null,"yuzhouaomi ","y","yz");
insert into STUDENT(ID,NAME,TID,CID) values(null, "lizi",1,1);
insert into STUDENT(ID,NAME,TID,CID) values(null, "lizi1",1,3);
insert into STUDENT(ID,NAME,TID,CID) values(null, "li",2,2);
insert into STUDENT(ID,NAME,TID,CID) values(null, "zhangsan",2,3);
insert into STUDENT(ID,NAME,TID,CID) values(null, "wangwu",2,4);
insert into TEACHER(ID,NAME) values(null,"mawenqiang");
insert into TEACHER(ID,NAME) values(null ,"houxiao");
insert into JoinManyToDateEntity(ID,ID_TO_MANY,ID_DATE) values(null,11,1);
insert into JoinManyToDateEntity(ID,ID_TO_MANY,ID_DATE) values(null,12,2);
insert into JoinManyToDateEntity(ID,ID_TO_MANY,ID_DATE) values(null,11,3);
insert into JoinManyToDateEntity(ID,ID_TO_MANY,ID_DATE) values(null,14,1);
insert into JoinManyToDateEntity(ID,ID_TO_MANY,ID_DATE) values(null,13,4);
insert into DATE_ENTITY(ID,DATE,DATE_NOT_NULL) values(null,1,5);
insert into DATE_ENTITY(ID,DATE,DATE_NOT_NULL) values(null,2,6);
insert into DATE_ENTITY(ID,DATE,DATE_NOT_NULL) values(null,3,7);
insert into DATE_ENTITY(ID,DATE,DATE_NOT_NULL) values(null,4,8);